# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
