# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempSite', '0002_auto_20160717_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
